### ISSUE TITLE
error plugin on Domoticz 2022.2

### ISSUE THREAD

**Issue by hofikhof** [sincze/Domoticz-Growatt-Webserver-Plugin#28]
2022-11-15 12:43:54.412  Status: GROWATT: Entering work loop.
2022-11-15 12:43:54.412  GROWATT: Worker thread started.
2022-11-15 12:43:54.412  Status: GROWATT: Started.
2022-11-15 12:43:54.651  Status: GROWATT: Initialized version 1.0.0, author 'sincze'
2022-11-15 12:43:54.657  GROWATT: Debug logging mask set to: QUEUE CONNECTION 
2022-11-15 12:43:54.667  Error: GROWATT: Call to function 'onStart' failed, exception details:
2022-11-15 12:43:54.694  Error: GROWATT: Traceback (most recent call last):
2022-11-15 12:43:54.694  Error: GROWATT:   File "/home/pi/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 264, in onStart
2022-11-15 12:43:54.694  Error: GROWATT:     _plugin.onStart()
2022-11-15 12:43:54.694  Error: GROWATT:   File "/home/pi/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 136, in onStart
2022-11-15 12:43:54.694  Error: GROWATT:     createDevices()
2022-11-15 12:43:54.694  Error: GROWATT:   File "/home/pi/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 353, in createDevices
2022-11-15 12:43:54.695  Error: GROWATT:     image = Images["Growatt"].ID # Get id from database
2022-11-15 12:43:54.695  Error: GROWATT: KeyError: 'Growatt'
2022-11-15 12:44:04.026  GROWATT: Pushing 'onHeartbeatCallback' on to queue
2022-11-15 12:44:04.077  GROWATT: Processing 'onHeartbeatCallback' message
2022-11-15 12:44:04.077  GROWATT: Calling message handler 'onHeartbeat' on 'module' type object.
2022-11-15 12:44:14.046  GROWATT: Pushing 'onHeartbeatCallback' on to queue
2022-11-15 12:44:14.097  GROWATT: Processing 'onHeartbeatCallback' message
2022-11-15 12:44:14.097  GROWATT: Calling message handler 'onHeartbeat' on 'module' type object.

**Comment by Tinus016** [comment]
Can you give this a try? https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/issues/4#issuecomment-582021216

**Comment by sincze** [comment]
Seems to be working with this fix if somebody can confirm I can update the pluging:
https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/issues/29#issuecomment-1321133498

**Comment by sincze** [comment]
Merged into V1.0.1
