### ISSUE TITLE
Call to function 'onMessage' failed

### ISSUE THREAD

**Issue by RolandTalstra** [sincze/Domoticz-Growatt-Webserver-Plugin#32]
Since 15/11 i'm receiving any data anymore,. The log shows 

2022-11-20 12:11:35.192 Error: Growatt : Call to function 'onMessage' failed, exception details:
2022-11-20 12:11:35.194 Error: Growatt : Traceback (most recent call last):
2022-11-20 12:11:35.194 Error: Growatt : File "/home/pi/domoticz/plugins/domoticz-growatt-webserver-pvoutput-plugin/plugin.py", line 276, in onMessage
2022-11-20 12:11:35.194 Error: Growatt : _plugin.onMessage(Connection, Data)
2022-11-20 12:11:35.194 Error: Growatt : File "/home/pi/domoticz/plugins/domoticz-growatt-webserver-pvoutput-plugin/plugin.py", line 173, in onMessage
2022-11-20 12:11:35.194 Error: Growatt : apiResponse = json.loads(strData)
2022-11-20 12:11:35.194 Error: Growatt : File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
2022-11-20 12:11:35.194 Error: Growatt : return _default_decoder.decode(s)
2022-11-20 12:11:35.194 Error: Growatt : File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
2022-11-20 12:11:35.194 Error: Growatt : obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2022-11-20 12:11:35.194 Error: Growatt : File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
2022-11-20 12:11:35.194 Error: Growatt : raise JSONDecodeError("Expecting value", s, err.value) from None
2022-11-20 12:11:35.194 Error: Growatt : json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sincze** [comment]
Without knowing your Domoticz version I honestly have no clue.
![image](https://user-images.githubusercontent.com/5776333/203841803-6b966064-c950-476b-a7b2-5392de14c5a6.png)

Did you try the current version ?

**Comment by RolandTalstra** [comment]
Agreed and apologies. This is very limited information

I just reinstalled and don't seem to errors in the log. I"ll see what tomorrow brings, and report back then.

Tnx for the response.

**Comment by sincze** [comment]
You're welcome. I noticed some errors with users switching to 2022.2 version of Domoticz.

**Comment by RolandTalstra** [comment]
I've noticed that the errors are gone, thanks to reinstalling your project. So, that's a step forward.

Unfortunately I'm not receiving any data.

Domoticz 2022.2
Python 3.7

I've tried all combinations in the Device 'Growatt - Inverter (kWh)' (Computer vs From device,  Usage vs Delivered') .
It keeps showing yesterday's install timestamp as the last update time.

I can see i'm delivering power at the moment, and also the Growatt portal shows generation of power, but alas nothing in Domoticz.

**Comment by RolandTalstra** [comment]
Was login error on my sad. Sorry to have bothered you with it.

**Comment by jan-vandenberg** [comment]
I do get these errors with Version: 2022.2 (every 3 minutes).

Any tips/pointers on how to fix these?


```
2023-02-08 23:54:31.167 Error: GroWatt Web: Call to function 'onMessage' failed, exception details:
2023-02-08 23:54:31.168 Error: GroWatt Web: Traceback (most recent call last):
2023-02-08 23:54:31.168 Error: GroWatt Web: File "/home/pi/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 276, in onMessage
2023-02-08 23:54:31.168 Error: GroWatt Web: _plugin.onMessage(Connection, Data)
2023-02-08 23:54:31.168 Error: GroWatt Web: File "/home/pi/domoticz/plugins/Domoticz-Growatt-Webserver-Plugin/plugin.py", line 173, in onMessage
2023-02-08 23:54:31.168 Error: GroWatt Web: apiResponse = json.loads(strData)
2023-02-08 23:54:31.168 Error: GroWatt Web: File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
2023-02-08 23:54:31.168 Error: GroWatt Web: return _default_decoder.decode(s)
2023-02-08 23:54:31.168 Error: GroWatt Web: File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
2023-02-08 23:54:31.168 Error: GroWatt Web: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-02-08 23:54:31.169 Error: GroWatt Web: File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
2023-02-08 23:54:31.169 Error: GroWatt Web: raise JSONDecodeError("Expecting value", s, err.value) from None
2023-02-08 23:54:31.169 Error: GroWatt Web: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jan-vandenberg** [comment]
This looks like it was the fix: https://github.com/sincze/Domoticz-Growatt-Webserver-Plugin/issues/29#issuecomment-1321133498

**Comment by sincze** [comment]
No Problem
